import { ShieldCheck, Beer, Flame } from 'lucide-react-native';

export const GENERIC_NAMES = [
    "O Bêbado", "A Santa", "O Tímido", "A Talarica",
    "A Vegana", "O Tik Toker", "O Herdeiro", "A Fofoqueira",
    "A Responsável", "O Desaparecido", "A Chorona", "O Inimigo do Fim",
    "O Coach", "O Cancelado", "O Gado", "A Influencer",

    "O DJ de Spotify", "A Mãe do Rolê", "O Inimigo do Banho", "A Barbie", "O Zé Palestrinha",
    "A Planta", "O Penetrate", "A Vip", "O Pão Duro", "A Biscoiteira",
    "O Rei do Pix", "A Sem Limites", "O Good Vibes", "A Surtada", "O Turista",

    "O Faria Limer", "A Crossfiteira", "O Agroboy", "A Gótica Suave", "O Maromba",
    "A Hippie", "O Crypto Bro", "A Pick Me Girl", "O Sigma", "A CLT Sofredora",
    "O Estagiário", "A Patrícia", "O Hipster", "A Indie", "O Gamer",

    "O Emocionado", "A Iludida", "O Dedo Podre", "A Fiscal de Postura", "O Dono da Razão",
    "A Rainha do Drama", "O Sedutor Barato", "A Bandida", "O Tio do Pavê", "A Maria Fifi",
    "O Mentiroso", "A Santa do Pau Oco", "O Cringe", "A E-girl", "O E-boy",

    "O Caloteiro", "A Barraqueira", "O Zé Povinho", "A Marmita de Casal", "O Fura Olho"
];

export const LEVELS = {
    fun: { id: 'fun', label: 'SÓ DIVERSÃO', color: '#22c55e', text: 'text-green-500', icon: ShieldCheck, desc: 'Sem álcool, sem humilhação.', price: 0 },
    prohibited: { id: 'prohibited', label: 'PROIBIDO (+16)', color: '#eab308', text: 'text-yellow-500', icon: Beer, desc: 'Bebida e leve constrangimento.', price: 0 },
    chaos: { id: 'chaos', label: 'VAI DAR RUIM (+18)', color: '#dc2626', text: 'text-red-600', icon: Flame, desc: 'Segredos, caos e +18.', price: 9.90 }
};

export const GAME_LIBRARY = [
    { id: 'eu_nunca', title: 'Eu Nunca', type: 'classic', isFree: true },
    { id: 'desafios_rapidos', title: 'Desafios Rápidos', type: 'action', isFree: true },
    { id: 'verdade_desafio', title: 'Verdade ou Desafio', type: 'classic', isFree: true },
    { id: 'kings', title: 'Rei da Mesa', type: 'card', isFree: true },
    { id: 'tribunal', title: 'Tribunal do Cancelamento', type: 'social', isFree: false, price: 9.90, desc: "Julgue seus amigos." },
    { id: 'provavel', title: 'Quem é Mais Provável?', type: 'expose', isFree: false, price: 9.90, desc: "Aponte o dedo e corra." }
];

export const DB_CONTENT = {
eu_nunca: [
        // ==============================================================================
        // NÍVEL: FUN (Gafes, Pequenas Mentiras e Tecnologia)
        // ==============================================================================
        { text: "Nunca stalkeei o ex do meu atual (ou o atual do meu ex).", level: 'fun' },
        { text: "Nunca curti uma foto antiga sem querer enquanto stalkeava.", level: 'fun' },
        { text: "Nunca fingi que estava digitando só para a pessoa esperar.", level: 'fun' },
        { text: "Nunca mandei print da conversa para a própria pessoa sem querer.", level: 'fun' },
        { text: "Nunca silenciei o grupo da família por 1 ano (ou arquivei para sempre).", level: 'fun' },
        { text: "Nunca postei stories fingindo estar feliz num rolê chato.", level: 'fun' },
        { text: "Nunca pesquisei meu próprio nome no Google.", level: 'fun' },
        { text: "Nunca removi marcação de foto porque saí feio(a).", level: 'fun' },
        { text: "Nunca usei foto de perfil de 5 anos atrás para parecer melhor.", level: 'fun' },
        { text: "Nunca ouvi um áudio no 2x e perdi metade da informação.", level: 'fun' },
        { text: "Nunca curti várias fotos antigas de alguém para chamar atenção.", level: 'fun' },
        { text: "Nunca dei tchau para alguém que não estava dando tchau para mim.", level: 'fun' },
        { text: "Nunca esqueci o nome da pessoa imediatamente após ser apresentado.", level: 'fun' },
        { text: "Nunca fingi que entendi o que alguém disse e só ri.", level: 'fun' },
        { text: "Nunca entrei na loja só para aproveitar o ar condicionado.", level: 'fun' },
        { text: "Nunca fingi demência quando encontrei conhecido na rua.", level: 'fun' },
        { text: "Nunca falei 'vamos marcar' sabendo que nunca ia marcar.", level: 'fun' },
        { text: "Nunca me senti atraído(a) pelo(a) pai/mãe de algum amigo.", level: 'fun' },
        { text: "Nunca chamei professor(a) ou chefe de 'mãe/pai'.", level: 'fun' },
        { text: "Nunca tropecei na rua e fingi que estava correndo (o trote do disfarce).", level: 'fun' },
        { text: "Nunca esperei a porta do elevador fechar para não ir com o vizinho.", level: 'fun' },
        { text: "Nunca fui a um encontro às cegas que foi um desastre.", level: 'fun' },
        { text: "Nunca saí correndo (literalmente) depois de um beijo ruim.", level: 'fun' },
        { text: "Nunca cheirei a própria roupa para ver se dava para usar de novo.", level: 'fun' },
        { text: "Nunca fui dormir sem escovar os dentes depois da balada.", level: 'fun' },
        { text: "Nunca usei shampoo a seco (ou talco) por 3 dias seguidos.", level: 'fun' },
        { text: "Nunca tirei 'caca' do nariz e limpei embaixo da cadeira/mesa.", level: 'fun' },
        { text: "Nunca soltei um pum e culpei o cachorro.", level: 'fun' },
        { text: "Nunca comi algo que tirei do dente.", level: 'fun' },
        { text: "Nunca deixei a louça suja até criar vida própria.", level: 'fun' },
        { text: "Nunca virei a roupa íntima do avesso para usar de novo.", level: 'fun' },
        { text: "Nunca roubei copo de balada ou bar.", level: 'fun' },
        { text: "Nunca disse 'já estou chegando' quando ainda estava no banho.", level: 'fun' },
        { text: "Nunca comi a comida de alguém na geladeira e não avisei.", level: 'fun' },
        { text: "Nunca criei um perfil fake para investigar alguém.", level: 'fun' },
        { text: "Nunca usei a conta de streaming de um ex (ou amigo) sem pagar.", level: 'fun' },
        { text: "Nunca devolvi uma roupa usada com a etiqueta escondida.", level: 'fun' },
        { text: "Nunca menti a idade para ganhar desconto.", level: 'fun' },
        { text: "Nunca peguei carona em conversa alheia no ônibus/metrô.", level: 'fun' },
        { text: "Nunca fingi estar doente para faltar compromisso.", level: 'fun' },
        { text: "Nunca cancelei o Uber porque o carro era feio.", level: 'fun' },
        { text: "Nunca marquei um encontro e dei bolo sem avisar.", level: 'fun' },
        { text: "Nunca dormi enquanto estava ficando com alguém.", level: 'fun' },
        { text: "Nunca usei uma fantasia que ninguém entendeu o que era.", level: 'fun' },
        { text: "Nunca assinei período grátis e esqueci de cancelar.", level: 'fun' },
        { text: "Nunca gastei o dinheiro do aluguel/conta com besteira.", level: 'fun' },
        { text: "Nunca comprei curso online e não assisti nem uma aula.", level: 'fun' },
        { text: "Nunca pesquisei doença no Google e achei que ia morrer.", level: 'fun' },
        { text: "Nunca tive crush em personagem de desenho animado.", level: 'fun' },
        { text: "Nunca vi meus pais em um momento de intimidade (trauma).", level: 'fun' },
        { text: "Nunca prometi dieta na segunda e comi pizza na terça.", level: 'fun' },
        { text: "Nunca briguei mentalmente com alguém no banho e ganhei.", level: 'fun' },
        { text: "Nunca tive medo de ir na cozinha de madrugada e saí correndo depois de apagar a luz.", level: 'fun' },
        { text: "Nunca tentei usar a força (Star Wars) para pegar o controle remoto.", level: 'fun' },

        // ==============================================================================
        // NÍVEL: PROHIBITED (Bebida, Toxidade Leve, Pegação Duvidosa)
        // ==============================================================================
        { text: "Nunca mandei mensagem para ex bêbado(a) de madrugada.", level: 'prohibited' },
        { text: "Nunca vomitei na balada e continuei bebendo depois.", level: 'prohibited' },
        { text: "Nunca acordei sem saber como cheguei em casa.", level: 'prohibited' },
        { text: "Nunca bebi o resto de bebida de um copo alheio (xepa).", level: 'prohibited' },
        { text: "Nunca prometi 'nunca mais eu bebo' e bebi no dia seguinte.", level: 'prohibited' },
        { text: "Nunca transei no banheiro de uma festa/bar.", level: 'prohibited' },
        { text: "Nunca perdi celular ou carteira porque estava muito louco(a).", level: 'prohibited' },
        { text: "Nunca fui carregado(a) pelos amigos para ir embora.", level: 'prohibited' },
        { text: "Nunca fiz xixi na rua e me molhei/sujei sem querer.", level: 'prohibited' },
        { text: "Nunca chorei em público ouvindo sofrência.", level: 'prohibited' },
        { text: "Nunca respondi um 'oi sumido(a)' sabendo que era cilada.", level: 'prohibited' },
        { text: "Nunca stalkeei atual de ex até descobrir o CPF.", level: 'prohibited' },
        { text: "Nunca fiquei com alguém só para fazer ciúmes.", level: 'prohibited' },
        { text: "Nunca tive um 'flashback' com ex e escondi dos amigos.", level: 'prohibited' },
        { text: "Nunca chorei por alguém que beijei apenas uma vez.", level: 'prohibited' },
        { text: "Nunca fiquei com alguém que hoje finjo que não conheço.", level: 'prohibited' },
        { text: "Nunca dei um nome falso para alguém na balada.", level: 'prohibited' },
        { text: "Nunca passei o número errado de propósito.", level: 'prohibited' },
        { text: "Nunca fiquei com amigo(a) de ex (a famosa talaricagem).", level: 'prohibited' },
        { text: "Nunca terminei (ou levei um pé) por WhatsApp.", level: 'prohibited' },
        { text: "Nunca tive um sonho proibidão com alguém desta roda.", level: 'prohibited' },
        { text: "Nunca fiquei com alguém do mesmo gênero (curiosidade ou não).", level: 'prohibited' },
        { text: "Nunca tive um sonho erótico com algum professor(a).", level: 'prohibited' },
        { text: "Nunca fiz simpatia para amarrar alguém.", level: 'prohibited' },
        { text: "Nunca fiquei com alguém na frente do ex de propósito.", level: 'prohibited' },
        { text: "Nunca beijei alguém e esqueci o nome 5 minutos depois.", level: 'prohibited' },
        { text: "Nunca transei no primeiro encontro.", level: 'prohibited' },
        { text: "Nunca fugi de um date fingindo emergência familiar.", level: 'prohibited' },
        { text: "Nunca fiz o 'Walk of Shame' (voltar pra casa de manhã com roupa de festa).", level: 'prohibited' },
        { text: "Nunca beijei 3 ou mais pessoas na mesma noite.", level: 'prohibited' },
        { text: "Nunca fiquei com alguém por interesse (carro, dinheiro, camarote).", level: 'prohibited' },
        { text: "Nunca levei alguém pra casa e me arrependi de manhã.", level: 'prohibited' },
        { text: "Nunca mandei nudes sem mostrar o rosto 'por segurança'.", level: 'prohibited' },
        { text: "Nunca mostrei nudes que recebi para os amigos.", level: 'prohibited' },
        { text: "Nunca beijei alguém desta roda.", level: 'prohibited' },
        { text: "Nunca usei técnicas de 'PUA' ou manipulação para ficar com alguém.", level: 'prohibited' },
        { text: "Nunca mexi no celular do namorado(a) dormindo.", level: 'prohibited' },
        { text: "Nunca postei foto biscoiteira com legenda de autoajuda.", level: 'prohibited' },
        { text: "Nunca apaguei Stories de vergonha moral.", level: 'prohibited' },
        { text: "Nunca fingi orgasmo para ir dormir logo.", level: 'prohibited' },
        { text: "Nunca dei 'ghosting' (sumi) em alguém que gostava de mim.", level: 'prohibited' },
        { text: "Nunca usei Tinder só para ganhar seguidores no Insta.", level: 'prohibited' },
        { text: "Nunca bloqueie e desbloqueie para chamar atenção.", level: 'prohibited' },
        { text: "Nunca mandei áudio gemendo no grupo da família/trabalho.", level: 'prohibited' },
        { text: "Nunca nadei pelado(a).", level: 'prohibited' },
        { text: "Nunca entrei de penetra em festa VIP.", level: 'prohibited' },
        { text: "Nunca saí de casa sem calcinha/cueca.", level: 'prohibited' },
        { text: "Nunca dei PT e precisei tomar glicose na veia.", level: 'prohibited' },
        { text: "Nunca flertei com segurança/policial para levar vantagem.", level: 'prohibited' },
        { text: "Nunca menti 'eu te amo' na hora H.", level: 'prohibited' },
        { text: "Nunca tive sonho erótico com namorado(a) de amigo(a).", level: 'prohibited' },
        { text: "Nunca fiz sexo em local público (praia, carro, cinema).", level: 'prohibited' },
        { text: "Nunca fiquei com autoridade (chefe, professor).", level: 'prohibited' },
        { text: "Nunca coloquei alguém nos 'Melhores Amigos' só para dar em cima.", level: 'prohibited' }, 

        // ==============================================================================
        // NÍVEL: CHAOS (Sexo Explícito, Crimes, Traição, Segredos Obscuros)
        // ==============================================================================
        { text: "Nunca fiz menage (sexo a 3).", level: 'chaos' },
        { text: "Nunca cheirei as roupas íntimas de outra pessoa.", level: 'chaos' },
        { text: "Nunca transei em local público com risco REAL de ser preso.", level: 'chaos' },
        { text: "Nunca gravei uma sex tape (e ainda tenho o vídeo).", level: 'chaos' },
        { text: "Nunca transei com alguém desta roda (e ninguém sabe).", level: 'chaos' },
        { text: "Nunca mandei nudes e eles vazaram na net/escola.", level: 'chaos' },
        { text: "Nunca transei na cama dos meus pais.", level: 'chaos' },
        { text: "Nunca furei a camisinha (ou menti sobre pílula) de propósito.", level: 'chaos' },
        { text: "Nunca tive uma experiência homoafetiva (sendo hétero declarado).", level: 'chaos' },
        { text: "Nunca recebi dinheiro ou presentes caros em troca de sexo.", level: 'chaos' },
        { text: "Nunca usei algemas, cordas ou mordaça na cama.", level: 'chaos' },
        { text: "Nunca fui pego no flagra transando pelos pais.", level: 'chaos' },
        { text: "Nunca transei com duas pessoas diferentes no mesmo dia (o famoso 'rodízio').", level: 'chaos' },
        { text: "Nunca transei no ambiente de trabalho.", level: 'chaos' },
        { text: "Nunca mandei nude para o grupo da família por engano.", level: 'chaos' },
        { text: "Nunca transei com alguém, fui no banheiro e fugi pela janela/porta.", level: 'chaos' },
        { text: "Nunca tive um acidente 'sujo' (anal) na hora H.", level: 'chaos' },
        { text: "Nunca transei menstruada(o) e deixei a cama parecendo um crime.", level: 'chaos' },
        { text: "Nunca fingi orgasmo tão bem que ganhei presente depois.", level: 'chaos' },
        { text: "Nunca transei com irmão/irmã de amigo meu.", level: 'chaos' },
        { text: "Nunca fui para um motel a pé.", level: 'chaos' },
        { text: "Nunca fui amante (sabendo que a pessoa era casada/namorava).", level: 'chaos' },
        { text: "Nunca traí e coloquei a culpa na bebida.", level: 'chaos' },
        { text: "Nunca fiquei com ex de melhor amigo(a) escondido.", level: 'chaos' },
        { text: "Nunca dei em cima do namorado(a) de alguém que está aqui.", level: 'chaos' },
        { text: "Nunca terminei namoro porque queria pegar outra pessoa específica.", level: 'chaos' },
        { text: "Nunca fucei o celular do parceiro e descobri traição (e não contei na hora).", level: 'chaos' },
        { text: "Nunca beijei alguém logo após vomitar (boca de lixo).", level: 'chaos' },
        { text: "Nunca destruí propriedade de ex por vingança.", level: 'chaos' },
        { text: "Nunca criei intriga/fofoca para separar um casal.", level: 'chaos' },
        { text: "Nunca flertei com pai ou mãe de amigo(a) (talaricagem geracional).", level: 'chaos' },
        { text: "Nunca fiquei com irmãos gêmeos (ou irmãos normais).", level: 'chaos' },
        { text: "Nunca fui detido(a) pela polícia.", level: 'chaos' },
        { text: "Nunca furtei algo de valor (loja, casa de amigo).", level: 'chaos' },
        { text: "Nunca usei drogas ilícitas em uma festa.", level: 'chaos' },
        { text: "Nunca dirigi bêbado(a) e bati o carro/ralada.", level: 'chaos' },
        { text: "Nunca fui expulso(a) de um lugar pelos seguranças.", level: 'chaos' },
        { text: "Nunca entrei em briga física de soco.", level: 'chaos' },
        { text: "Nunca quebrei algo caro na casa dos outros e escondi.", level: 'chaos' },
        { text: "Nunca falsifiquei documento (RG, atestado).", level: 'chaos' },
        { text: "Nunca dei calote em conta de bar/restaurante.", level: 'chaos' },
        { text: "Nunca vandalizei patrimônio público.", level: 'chaos' },
        { text: "Nunca caguei nas calças depois de adulto.", level: 'chaos' },
        { text: "Nunca entupi o vaso na casa do date e não tinha água.", level: 'chaos' },
        { text: "Nunca vomitei na boca de alguém beijando/transando.", level: 'chaos' },
        { text: "Nunca tive que ir pro hospital tirar algo enfiado no corpo.", level: 'chaos' },
        { text: "Nunca manchei a roupa de menstruação em público e não tinha blusa pra amarrar.", level: 'chaos' },
        { text: "Nunca acordei do lado de um completo estranho.", level: 'chaos' },
        { text: "Nunca passei uma DST para alguém.", level: 'chaos' },
        { text: "Nunca fui flagrado me masturbando.", level: 'chaos' },
        { text: "Nunca urinei na cama de outra pessoa bêbado(a).", level: 'chaos' },
        { text: "Nunca tive diarreia explosiva em um encontro.", level: 'chaos' },
        { text: "Nunca achei que estava grávida).", level: 'chaos' }, 
        { text: "Nunca fingi gravidez para segurar alguém.", level: 'chaos' },
        { text: "Nunca mandei 'nudes' que na verdade eram fotos da internet.", level: 'chaos' } 
    ],
desafios_rapidos: [
        // ==============================================================================
        // NÍVEL: FUN (Quebra-Gelo, Vergonha Alheia, Mímicas Ridículas)
        // ==============================================================================
        { text: "Imite uma galinha botando ovo por 10 segundos.", level: 'fun' },
        { text: "Fale com sotaque gringo até a próxima rodada.", level: 'fun' },
        { text: "Troque de lugar com a pessoa à sua esquerda.", level: 'fun' },
        { text: "Deixe a pessoa à sua direita pentear seu cabelo como quiser.", level: 'fun' },
        { text: "Faça uma declaração de amor dramática para uma cadeira.", level: 'fun' },
        { text: "Imite a risada de alguém da roda.", level: 'fun' },
        { text: "Mande um áudio miando no grupo da família.", level: 'fun' },
        { text: "Dance 'na boquinha da garrafa' (sem música) por 20 segundos.", level: 'fun' },
        { text: "Faça uma massagem no ombro da pessoa à sua esquerda.", level: 'fun' },
        { text: "Tire uma selfie fazendo a cara mais feia possível e mostre.", level: 'fun' },
        { text: "Lamba o cotovelo (ou tente) por 10 segundos.", level: 'fun' },
        { text: "Fale tudo cantando estilo ópera até sua próxima vez.", level: 'fun' },
        { text: "Deixe alguém te fazer cócegas por 15 segundos sem rir.", level: 'fun' },
        { text: "Cheire o pé da pessoa à sua direita e dê uma nota.", level: 'fun' },
        { text: "Imite um T-Rex arrumando a cama.", level: 'fun' },
        { text: "Faça o quadradinho de 8 (ou tente).", level: 'fun' },
        { text: "Ligue para uma pizzaria e pergunte se vendem pneu.", level: 'fun' },
        { text: "Mande um emoji de berinjela 🍆 para o último contato do WhatsApp.", level: 'fun' },
        { text: "Deixe o grupo escolher uma pose para você postar nos stories agora.", level: 'fun' },
        { text: "Grite 'EU AMO PAGODE' na janela.", level: 'fun' },
        { text: "Faça 10 flexões (ou agachamentos) agora.", level: 'fun' },
        { text: "Ajoelhe e peça desculpas por ser feio/a (atuação).", level: 'fun' },
        { text: "Imite um bebê chorando até alguém mandar parar.", level: 'fun' },
        { text: "Deixe alguém desenhar um bigode em você com caneta/lápis.", level: 'fun' },
        { text: "Fique vesgo e tente ler uma mensagem no celular.", level: 'fun' },
        { text: "Faça um brinde em homenagem ao seu próprio ego.", level: 'fun' },
        { text: "Ande de 'carrinho de mão' com alguém pela sala.", level: 'fun' },
        { text: "Coloque um cubo de gelo dentro da blusa até derreter.", level: 'fun' },
        { text: "Venda um objeto da sala como se fosse um produto Polishop.", level: 'fun' },
        { text: "Imite o gemidão do WhatsApp bem alto.", level: 'fun' },
        { text: "Fale o alfabeto de trás para frente (ou beba se errar).", level: 'fun' },
        { text: "Faça uma 'crítica construtiva' sincera para todos da roda (sem repetir).", level: 'fun' },
        { text: "Use o sapato de alguém como telefone por 1 rodada.", level: 'fun' },
        { text: "Faça uma cara de sedução para a parede.", level: 'fun' },
        { text: "Tente lamber seu próprio nariz.", level: 'fun' },
        { text: "Fique em um pé só até sua próxima vez.", level: 'fun' },
        { text: "Dublagem: alguém fala e você mexe a boca.", level: 'fun' },
        { text: "Faça um poema rimando 'amor' com 'dor' e 'fedorento'.", level: 'fun' },
        { text: "Imite um cachorro fazendo xixi no poste.", level: 'fun' },
        { text: "Conte uma piada ruim. Se ninguém rir, pague 10 polichinelos (depois de beber um shot e dar 5 giros).", level: 'fun' },
        { text: "Gire 10 vezes e tente andar em linha reta.", level: 'fun' },
        { text: "Deixe alguém fazer um penteado ridículo em você.", level: 'fun' },
        { text: "Fale 'Pudim de Passas' com a língua para fora.", level: 'fun' },
        { text: "Dance valsa com uma vassoura (ou objeto imaginário).", level: 'fun' },
        { text: "Finja que está sendo eletrocutado.", level: 'fun' },
        { text: "Aponte para quem você levaria para uma ilha deserta.", level: 'fun' },
        { text: "Faça mímica de um filme para o grupo adivinhar.", level: 'fun' },
        { text: "Cante o Hino Nacional (só o refrão) gargarejando água.", level: 'fun' },
        { text: "Fique de mãos dadas com a pessoa da esquerda por 1 rodada.", level: 'fun' },
        { text: "Equilibre um copo (vazio) na cabeça por 1 minuto.", level: 'fun' },

        // ==============================================================================
        // NÍVEL: PROHIBITED (Bebida, Contato Físico, Celular Aberto)
        // ==============================================================================
        { text: "Beba um gole sem usar as mãos.", level: 'prohibited' },
        { text: "Sente no colo da pessoa à sua direita por 2 rodadas.", level: 'prohibited' },
        { text: "Vire um shot de bebida pura (sem fazer careta).", level: 'prohibited' },
        { text: "Mostre a última foto da sua galeria (sem explicar).", level: 'prohibited' },
        { text: "Deixe alguém ler a primeira conversa do seu WhatsApp.", level: 'prohibited' },
        { text: "Dê um beijo no pescoço da pessoa à esquerda.", level: 'prohibited' },
        { text: "Faça uma lap dance (dança no colo) de 10s em alguém.", level: 'prohibited' },
        { text: "Troque de camisa com a pessoa à sua frente.", level: 'prohibited' },
        { text: "Beba um gole da bebida de cada pessoa da roda.", level: 'prohibited' },
        { text: "Deixe o grupo fazer um drink misturado para você virar.", level: 'prohibited' },
        { text: "Faça 'body shot' (beber no umbigo/corpo) em alguém.", level: 'prohibited' },
        { text: "Mostre seu histórico de pesquisa do Google.", level: 'prohibited' },
        { text: "Morda levemente a orelha de alguém.", level: 'prohibited' },
        { text: "Coloque a mão dentro da camisa da pessoa à direita (no ombro rs).", level: 'prohibited' },
        { text: "Tire uma peça de roupa (acessórios não contam, nem a meia do seu pé direito! Não sabe jogar,não desce pro play).", level: 'prohibited' },
        { text: "Beije a bochecha de todos do gênero oposto (ou de interesse - Só você sabe).", level: 'prohibited' },
        { text: "Mostre sua foto de RG ou CNH para todos.", level: 'prohibited' },
        { text: "Dê um selinho na pessoa que você acha mais bonita.", level: 'prohibited' },
        { text: "Deixe alguém te dar um tapa na cara (força média).", level: 'prohibited' },
        { text: "Beba 3 goles seguidos sem respirar.", level: 'prohibited' },
        { text: "Mande 'Saudades' para o terceiro contato recente do Whats.", level: 'prohibited' },
        { text: "Deixe a pessoa à esquerda postar um status no seu WhatsApp.", level: 'prohibited' },
        { text: "Receba uma massagem nas costas de alguém por 1 minuto.", level: 'prohibited' },
        { text: "Fale o nome de 3 pessoas que você já beijou. (A roda precisa conhecer pô)", level: 'prohibited' },
        { text: "Escolha alguém para beber metade do seu copo.", level: 'prohibited' },
        { text: "Dê um 'cheiro' cangote de alguém e gema.", level: 'prohibited' },
        { text: "Mostre seus DMs (Directs) do Instagram recentes.", level: 'prohibited' },
        { text: "Passe gelo na nuca de alguém com a boca.", level: 'prohibited' },
        { text: "Abrace a pessoa à sua frente e sussurre algo estranho.", level: 'prohibited' },
        { text: "Fique de conchinha com alguém no chão por 1 minuto.", level: 'prohibited' },
        { text: "Mande um áudio cantando funk para o seu chefe/pai.", level: 'prohibited' },
        { text: "Deixe alguém ver sua lista de bloqueados.", level: 'prohibited' },
        { text: "Faça uma pose sexy no chão e deixe tirarem foto.", level: 'prohibited' },
        { text: "Beba de mãos dadas com alguém (os dois bebem).", level: 'prohibited' },
        { text: "Chupei o dedo da pessoa à direita por 5 segundos.", level: 'prohibited' },
        { text: "Escolha duas pessoas para se beijarem (selinho).", level: 'prohibited' },
        { text: "Revele a cor da sua roupa íntima (ou mostre a alça/elástico).", level: 'prohibited' },
        { text: "Lamba o rosto de alguém.", level: 'prohibited' },
        { text: "Permita que alguém te dê um chupão no braço.", level: 'prohibited' },
        { text: "Simule uma posição sexual (de roupa) com uma cadeira.", level: 'prohibited' },
        { text: "Coloque o dedo na boca de alguém e deixe a pessoa chupar.", level: 'prohibited' },
        { text: "Dê um beijo triplo (você e mais dois).", level: 'prohibited' },
        { text: "Deixe alguém escrever algo na sua testa com batom.", level: 'prohibited' },
        { text: "Coma algo de forma erótica olhando pra alguém.", level: 'prohibited' },
        { text: "Fale qual a parte do corpo da pessoa à direita te excita.", level: 'prohibited' },
        { text: "Beba um shot de tequila (ou o que tiver) com sal e limão.", level: 'prohibited' },
        { text: "Faça 20 agachamentos enquanto alguém segura sua cintura.", level: 'prohibited' },
        { text: "Poste 'Estou grávida' (ou 'Vou ser pai') e apague em 5 min.", level: 'prohibited' },
        { text: "Ligue para um amigo e diga que está apaixonado por ele.", level: 'prohibited' },
        { text: "Tire a camisa (se for homem) ou sutiã por cima da blusa (mulher).", level: 'prohibited' },

        // ==============================================================================
        // NÍVEL: CHAOS (Destruição de Dignidade, Beijo, Segredos e Risco Real)
        // ==============================================================================
        { text: "Mande 'Eu ainda te amo' para o seu ex agora.", level: 'chaos' },
        { text: "Dê um beijo de língua na pessoa à sua esquerda.", level: 'chaos' },
        { text: "Mostre uma nude sua (ou foto sensual) para a roda por 1 seg.", level: 'chaos' },
        { text: "Ligue para a mãe/pai e diga que foi preso.", level: 'chaos' },
        { text: "Vire o copo inteiro de bebida (fundo branco).", level: 'chaos' },
        { text: "Deixe o grupo mandar uma mensagem para quem eles quiserem do seu cel.", level: 'chaos' },
        { text: "Beije a pessoa que a roda escolher.", level: 'chaos' },
        { text: "Tire uma peça de roupa e jogue pela janela (ou deixe alguém esconder).", level: 'chaos' },
        { text: "Deixe alguém lamber seu pescoço.", level: 'chaos' },
        { text: "Poste a foto mais feia da sua galeria no Story agora.", level: 'chaos' },
        { text: "Mande mensagem para o crush: 'Quero você agora'.", level: 'chaos' },
        { text: "Faça um '7 minutos no paraíso' (trancado no banheiro) com alguém.", level: 'chaos' },
        { text: "Coloque a mão dentro da calça de alguém por 10 segundos.", level: 'chaos' },
        { text: "Dê um beijo na boca da pessoa que você menos conhece aqui.", level: 'chaos' },
        { text: "Deixe alguém dar um tapa na sua bunda.", level: 'chaos' },
        { text: "Revele com quem da roda você transaria.", level: 'chaos' },
        { text: "Deixe alguém cuspir bebida na sua boca (bird feeding).", level: 'chaos' },
        { text: "Mande um nude (com visualização única) para um contatinho.", level: 'chaos' },
        { text: "Fique de roupas íntimas até o fim do jogo.", level: 'chaos' },
        { text: "Beije o mamilo de alguém (por cima da roupa se preferir).", level: 'chaos' },
        { text: "Conte seu segredo sexual mais obscuro.", level: 'chaos' },
        { text: "Conte um fetiche.", level: 'chaos' },
        { text: "Ligue para o último número discado e gema quando atenderem.", level: 'chaos' },
        { text: "Deixe alguém passar gelo no seu corpo inteiro (por dentro da roupa).", level: 'chaos' },
        { text: "Dê um beijo de cinema na pessoa à sua frente.", level: 'chaos' },
        { text: "Coma algo da boca de outra pessoa (passar comida).", level: 'chaos' },
        { text: "Deixe alguém depilar uma parte do seu corpo (perna/braço) com fita.", level: 'chaos' },
        { text: "Mande mensagem pro ex: 'Tô com sdds da sua cama'.", level: 'chaos' },
        { text: "Revele quem você 'mataria, beijaria ou casaria' da roda.", level: 'chaos' },
        { text: "Deixe o grupo ver suas fotos ocultas/lixeira do celular.", level: 'chaos' },
        { text: "Faça sexo oral em uma fruta (banana/pepino) olhando nos olhos de alguém.", level: 'chaos' },
        { text: "Beije a parte interna da coxa de alguém.", level: 'chaos' },
        { text: "Mande foto do seu pé para um feticheiro (ou random) no Insta.", level: 'chaos' },
        { text: "Deixe alguém morder seu lábio inferior.", level: 'chaos' },
        { text: "Simule um orgasmo alto por 15 segundos.", level: 'chaos' },
        { text: "Troque de roupa íntima com alguém (se tiver coragem).", level: 'chaos' },
        { text: "Mande 'Quero te dar' para a 1ª pessoa que visualizar seu story.", level: 'chaos' },
        { text: "Deixe alguém cuspir na sua mão e você tem que lamber.", level: 'chaos' },
        { text: "Revele qual amigo(a) da roda você acha mais 'pegável'.", level: 'chaos' },
        { text: "Faça um vídeo rebolando e envie para algum grupo.", level: 'chaos' },
        { text: "Ligue para um ex e pergunte 'Por que a gente terminou?'.", level: 'chaos' },
        { text: "Deixe alguém te algemar (ou amarrar) por 1 rodada.", level: 'chaos' },
        { text: "Beije a pessoa à direita e à esquerda (sanduíche).", level: 'chaos' },
        { text: "Mande áudio descrevendo sua roupa íntima para um colega.", level: 'chaos' },
        { text: "Fique vendado e deixe alguém te beijar (adivinhe quem foi).", level: 'chaos' }
    ],
verdade_desafio: [
        // ==============================================================================
        // NÍVEL: FUN (Vergonha Alheia, Infância, Imitacões)
        // ==============================================================================
        { type: 'verdade', text: "Qual foi o motivo mais ridículo pelo qual você chorou?", level: 'fun' },
        { type: 'desafio', text: "Imite uma galinha botando ovo por 20 segundos.", level: 'fun' },
        { type: 'verdade', text: "Qual a música mais vergonhosa na sua playlist agora?", level: 'fun' },
        { type: 'desafio', text: "Fale com sotaque de novela mexicana até a próxima rodada.", level: 'fun' },
        { type: 'verdade', text: "Qual foi a pior compra que você já fez?", level: 'fun' },
        { type: 'desafio', text: "Deixe alguém pentear seu cabelo do jeito que quiser.", level: 'fun' },
        { type: 'verdade', text: "Qual desenho animado você ainda assiste ou gosta?", level: 'fun' },
        { type: 'desafio', text: "Faça uma serenata dramática para uma vassoura (ou objeto).", level: 'fun' },
        { type: 'verdade', text: "Qual apelido vergonhoso seus pais te deram?", level: 'fun' },
        { type: 'desafio', text: "Dance a 'Macarena' sem música e em silêncio.", level: 'fun' },
        { type: 'verdade', text: "Você já treinou beijo no espelho ou na mão?", level: 'fun' },
        { type: 'desafio', text: "Lamba seu próprio cotovelo (ou tente).", level: 'fun' },
        { type: 'verdade', text: "Qual a mentira mais boba que você contou para faltar no trabalho/aula?", level: 'fun' },
        { type: 'desafio', text: "Deixe alguém te fazer cócegas por 10 segundos.", level: 'fun' },
        { type: 'verdade', text: "Qual celebridade 'feia' você acha bonita?", level: 'fun' },
        { type: 'desafio', text: "Faça uma cara de peixe e fique assim por 1 minuto.", level: 'fun' },
        { type: 'verdade', text: "O que você faria se fosse invisível por um dia?", level: 'fun' },
        { type: 'desafio', text: "Gire 10 vezes e tente caminhar em linha reta.", level: 'fun' },
        { type: 'verdade', text: "Qual a foto mais constrangedora no seu celular?", level: 'fun' },
        { type: 'desafio', text: "Coloque um cubo de gelo dentro da blusa.", level: 'fun' },
        { type: 'verdade', text: "Você fala sozinho? Sobre o quê?", level: 'fun' },
        { type: 'desafio', text: "Imite a risada de alguém da roda.", level: 'fun' },
        { type: 'verdade', text: "Qual foi seu pior corte de cabelo?", level: 'fun' },
        { type: 'desafio', text: "Faça um rap improvisado sobre a pessoa à sua direita.", level: 'fun' },
        { type: 'verdade', text: "Você já caiu na rua na frente de todo mundo?", level: 'fun' },
        { type: 'desafio', text: "Mande um áudio miando para o último grupo do WhatsApp.", level: 'fun' },
        { type: 'verdade', text: "Qual comida estranha você adora?", level: 'fun' },
        { type: 'desafio', text: "Fique vesgo e mande um beijo para a roda.", level: 'fun' },
        { type: 'verdade', text: "Qual seu medo mais irracional (palhaço, escuro, etc)?", level: 'fun' },
        { type: 'desafio', text: "Deixe alguém desenhar um bigode em você (com caneta ou imaginário).", level: 'fun' },
        { type: 'verdade', text: "Você já stalkeou alguém por horas e curtiu algo sem querer?", level: 'fun' },
        { type: 'desafio', text: "Fale tudo cantando pelas próximas 3 rodadas.", level: 'fun' },
        { type: 'verdade', text: "Qual a coisa mais nojenta que você já fez e ninguém sabe?", level: 'fun' },
        { type: 'desafio', text: "Faça 10 polichinelos agora.", level: 'fun' },
        { type: 'verdade', text: "Quem desta roda você levaria para uma ilha deserta?", level: 'fun' },
        { type: 'desafio', text: "Cheire o pé da pessoa à sua esquerda.", level: 'fun' },
        { type: 'verdade', text: "Você já fingiu estar doente para não sair?", level: 'fun' },
        { type: 'desafio', text: "Faça uma massagem no ombro de quem está à sua direita.", level: 'fun' },
        { type: 'verdade', text: "Qual foi o presente mais feio que você já ganhou e fingiu gostar?", level: 'fun' },
        { type: 'desafio', text: "Deixe alguém postar uma foto zuada no seu Story (apague em 5 min).", level: 'fun' },
        { type: 'verdade', text: "Você já usou a escova de dentes de outra pessoa?", level: 'fun' },
        { type: 'desafio', text: "Tente colocar o pé atrás da cabeça.", level: 'fun' },
        { type: 'verdade', text: "Qual foi a pior cantada que você já usou ou recebeu?", level: 'fun' },
        { type: 'desafio', text: "Finja que está brigando com um fantasma.", level: 'fun' },
        { type: 'verdade', text: "O que você faria se ganhasse na loteria hoje?", level: 'fun' },
        { type: 'desafio', text: "Imite um bebê chorando muito alto.", level: 'fun' },
        { type: 'verdade', text: "Qual personagem de filme você seria?", level: 'fun' },
        { type: 'desafio', text: "Beba um copo d'água sem usar as mãos.", level: 'fun' },
        { type: 'verdade', text: "Você ronca ou fala dormindo?", level: 'fun' },
        { type: 'desafio', text: "Faça uma pose de modelo e deixe tirarem foto.", level: 'fun' },

        // ==============================================================================
        // NÍVEL: PROHIBITED (Crushes, Bebida, Exposição Leve)
        // ==============================================================================
        { type: 'verdade', text: "Qual foi a pior coisa que você fez bêbado(a)?", level: 'prohibited' },
        { type: 'desafio', text: "Vire um shot de bebida pura.", level: 'prohibited' },
        { type: 'verdade', text: "Quem da roda você beijaria se o mundo acabasse hoje?", level: 'prohibited' },
        { type: 'desafio', text: "Dê um selinho na pessoa à sua direita.", level: 'prohibited' },
        { type: 'verdade', text: "Você já ficou com alguém comprometido?", level: 'prohibited' },
        { type: 'desafio', text: "Deixe alguém ler a última mensagem do seu WhatsApp.", level: 'prohibited' },
        { type: 'verdade', text: "Qual a parte do corpo que você mais gosta em si mesmo?", level: 'prohibited' },
        { type: 'desafio', text: "Tire uma peça de roupa.", level: 'prohibited' },
        { type: 'verdade', text: "Você voltaria com algum ex? Qual?", level: 'prohibited' },
        { type: 'desafio', text: "Mande um 'Oi sumido' para o terceiro contato do WhatsApp.", level: 'prohibited' },
        { type: 'verdade', text: "Você já mentiu para conseguir ficar com alguém?", level: 'prohibited' },
        { type: 'desafio', text: "Faça uma lap dance (roupa) em alguém da roda.", level: 'prohibited' },
        { type: 'verdade', text: "Qual foi o lugar mais estranho onde você já ficou com alguém?", level: 'prohibited' },
        { type: 'desafio', text: "Beije o pescoço da pessoa à sua esquerda.", level: 'prohibited' },
        { type: 'verdade', text: "Você já mandou nudes? Para quem?", level: 'prohibited' },
        { type: 'desafio', text: "Mostre a última foto da sua galeria (sem explicar).", level: 'prohibited' },
        { type: 'verdade', text: "Qual característica física te atrai primeiro?", level: 'prohibited' },
        { type: 'desafio', text: "Sente no colo de alguém por 2 rodadas.", level: 'prohibited' },
        { type: 'verdade', text: "Você já teve um sonho erótico com alguém daqui?", level: 'prohibited' },
        { type: 'desafio', text: "Deixe alguém te dar um chupão no braço.", level: 'prohibited' },
        { type: 'verdade', text: "Quem aqui se veste pior?", level: 'prohibited' },
        { type: 'desafio', text: "Beba um gole da bebida de cada pessoa da roda.", level: 'prohibited' },
        { type: 'verdade', text: "Você já ficou com amigo de ex?", level: 'prohibited' },
        { type: 'desafio', text: "Lamba o rosto de alguém.", level: 'prohibited' },
        { type: 'verdade', text: "Qual foi seu recorde de pessoas numa noite?", level: 'prohibited' },
        { type: 'desafio', text: "Mande um áudio gemendo no grupo dos amigos.", level: 'prohibited' },
        { type: 'verdade', text: "Você já fingiu orgasmo?", level: 'prohibited' },
        { type: 'desafio', text: "Faça uma massagem sensual nas costas de alguém.", level: 'prohibited' },
        { type: 'verdade', text: "O que te faz broxar na hora?", level: 'prohibited' },
        { type: 'desafio', text: "Deixe alguém morder sua orelha.", level: 'prohibited' },
        { type: 'verdade', text: "Você prefere luz acesa ou apagada?", level: 'prohibited' },
        { type: 'desafio', text: "Troque de camisa com alguém da roda.", level: 'prohibited' },
        { type: 'verdade', text: "Você já nadou pelado?", level: 'prohibited' },
        { type: 'desafio', text: "Beba 3 goles seguidos sem respirar.", level: 'prohibited' },
        { type: 'verdade', text: "Qual a cor da sua roupa íntima agora?", level: 'prohibited' },
        { type: 'desafio', text: "Mostre a roupa íntima (puxe o elástico).", level: 'prohibited' },
        { type: 'verdade', text: "Você já foi pego no flagra? Por quem?", level: 'prohibited' },
        { type: 'desafio', text: "Faça um body shot (beber no corpo) em alguém.", level: 'prohibited' },
        { type: 'verdade', text: "Quem da roda beija melhor (ou parece beijar)?", level: 'prohibited' },
        { type: 'desafio', text: "Dê um beijo triplo (você e mais dois).", level: 'prohibited' },
        { type: 'verdade', text: "Você tem algum fetiche? Qual?", level: 'prohibited' },
        { type: 'desafio', text: "Deixe alguém te dar um tapa na bunda.", level: 'prohibited' },
        { type: 'verdade', text: "Você sairia com alguém por dinheiro?", level: 'prohibited' },
        { type: 'desafio', text: "Mande nudes (fake ou real) para alguém (visualização única).", level: 'prohibited' },
        { type: 'verdade', text: "O que você mudaria no seu corpo?", level: 'prohibited' },
        { type: 'desafio', text: "Passe um cubo de gelo no pescoço de alguém com a boca.", level: 'prohibited' },
        { type: 'verdade', text: "Você já traiu? Por quê?", level: 'prohibited' },
        { type: 'desafio', text: "Fique de mãos dadas com seu 'crush' da roda até a próxima vez.", level: 'prohibited' },
        { type: 'verdade', text: "Qual foi a pessoa mais velha que você já pegou?", level: 'prohibited' },
        { type: 'desafio', text: "Simule uma posição sexual com uma cadeira.", level: 'prohibited' },

        // ==============================================================================
        // NÍVEL: CHAOS (Segredos Sombrios, Beijo Real, Perigo)
        // ==============================================================================
        { type: 'verdade', text: "Quem desta roda você transaria agora?", level: 'chaos' },
        { type: 'desafio', text: "Dê um beijo de língua na pessoa à sua esquerda.", level: 'chaos' },
        { type: 'verdade', text: "Qual foi seu sonho erótico mais bizarro?", level: 'chaos' },
        { type: 'desafio', text: "Tire duas peças de roupa.", level: 'chaos' },
        { type: 'verdade', text: "Você já fez sexo a três? Com quem faria da roda?", level: 'chaos' },
        { type: 'desafio', text: "Mande 'Ainda te amo' para o seu ex.", level: 'chaos' },
        { type: 'verdade', text: "Qual a coisa mais ilegal que você já fez?", level: 'chaos' },
        { type: 'desafio', text: "Vire o copo (fundo branco).", level: 'chaos' },
        { type: 'verdade', text: "Você já pegou alguma DST?", level: 'chaos' },
        { type: 'desafio', text: "Deixe o grupo mandar uma mensagem do seu celular pra quem quiser.", level: 'chaos' },
        { type: 'verdade', text: "Você sente atração por alguém comprometido desta roda?", level: 'chaos' },
        { type: 'desafio', text: "Beije a pessoa que a roda escolher.", level: 'chaos' },
        { type: 'verdade', text: "Qual foi a pior traição que você já cometeu?", level: 'chaos' },
        { type: 'desafio', text: "Deixe alguém lamber seu pescoço.", level: 'chaos' },
        { type: 'verdade', text: "Você já transou no trabalho? Onde?", level: 'chaos' },
        { type: 'desafio', text: "Fique de roupa íntima até o fim do jogo.", level: 'chaos' },
        { type: 'verdade', text: "Quanto você ganha por mês?", level: 'chaos' },
        { type: 'desafio', text: "Mostre uma nude sua (ou foto sensual) para a roda por 2 seg.", level: 'chaos' },
        { type: 'verdade', text: "Você odeia alguém que está aqui? Quem?", level: 'chaos' },
        { type: 'desafio', text: "Ligue para a mãe/pai e diga que vai ser pai/mãe.", level: 'chaos' },
        { type: 'verdade', text: "Qual foi a última vez que você se masturbou?", level: 'chaos' },
        { type: 'desafio', text: "Deixe alguém colocar a mão dentro da sua calça/short.", level: 'chaos' },
        { type: 'verdade', text: "Você já teve experiência homossexual? Conte.", level: 'chaos' },
        { type: 'desafio', text: "Dê um chupão no pescoço de alguém (marca real).", level: 'chaos' },
        { type: 'verdade', text: "Qual a coisa mais nojenta que você faria por 1 milhão?", level: 'chaos' },
        { type: 'desafio', text: "Coma uma banana (ou pepino) de forma erótica.", level: 'chaos' },
        { type: 'verdade', text: "Você já gravou uma sex tape? Com quem?", level: 'chaos' },
        { type: 'desafio', text: "Beije o mamilo de alguém (por cima da roupa, se preferir).", level: 'chaos' },
        { type: 'verdade', text: "Quem você mataria, beijaria e casaria desta roda?", level: 'chaos' },
        { type: 'desafio', text: "Deixe alguém cuspir bebida na sua boca.", level: 'chaos' },
        { type: 'verdade', text: "Você já furou camisinha de propósito?", level: 'chaos' },
        { type: 'desafio', text: "Mande mensagem pro crush: 'Quero você na minha cama'.", level: 'chaos' },
        { type: 'verdade', text: "Qual seu maior segredo que poderia destruir sua vida?", level: 'chaos' },
        { type: 'desafio', text: "Faça '7 minutos no paraíso' (trancado no banheiro) com alguém.", level: 'chaos' },
        { type: 'verdade', text: "Você já pagou por sexo?", level: 'chaos' },
        { type: 'desafio', text: "Lamba o dedo do pé de alguém.", level: 'chaos' },
        { type: 'verdade', text: "Você já fez anal? Gostou?", level: 'chaos' },
        { type: 'desafio', text: "Simule um orgasmo alto e convincente.", level: 'chaos' },
        { type: 'verdade', text: "Você já roubou dinheiro da carteira dos seus pais?", level: 'chaos' },
        { type: 'desafio', text: "Beba um shot de vinagre ou óleo.", level: 'chaos' },
        { type: 'verdade', text: "Qual a pessoa mais feia que você já pegou?", level: 'chaos' },
        { type: 'desafio', text: "Troque de roupa íntima com alguém (se tiver coragem).", level: 'chaos' },
        { type: 'verdade', text: "Você já desejou a morte de alguém?", level: 'chaos' },
        { type: 'desafio', text: "Deixe alguém depilar uma parte do seu corpo com fita.", level: 'chaos' },
        { type: 'verdade', text: "Você já foi amante? Conte a história.", level: 'chaos' },
        { type: 'desafio', text: "Sente no rosto de alguém (vestido) por 5 segundos.", level: 'chaos' },
        { type: 'verdade', text: "Você tem inveja de alguém aqui? De quê?", level: 'chaos' },
        { type: 'desafio', text: "Mostre seu histórico de pesquisa do Google (sem apagar).", level: 'chaos' },
        { type: 'verdade', text: "Quem da roda você acha mais inútil?", level: 'chaos' },
        { type: 'desafio', text: "Mande 'Quero te dar' para a primeira pessoa que viu seu Story.", level: 'chaos' },
    ],
kings: [
        // --- NÍVEL: FUN (Ações simples, jogos de grupo) ---
        { card: 'A', rule: 'CASCATA: Todos bebem! Começa por você.', type: 'action' },
        { card: '2', rule: 'O Justiceiro: Escolha alguém para beber 2 goles.', type: 'target' },
        { card: '3', rule: 'O Castigo: Você bebe 3 goles (ou 1 shot).', type: 'self' },
        { card: '4', rule: 'As Damas: Todas as mulheres da roda bebem.', type: 'action' },
        { card: '6', rule: 'Os Cavalheiros: Todos os homens da roda bebem.', type: 'action' },
        { card: '7', rule: 'O Teto: Mãos para o alto! O último a levantar bebe.', type: 'action' },
        { card: '8', rule: 'O Parceiro: Escolha uma dupla para beber com você.', type: 'target' },
        { card: '9', rule: 'A Rima: Fale uma palavra. O próximo rima.', type: 'mini-game' },
        { card: '10', rule: 'A Categoria: Escolha um tema. Quem travar bebe.', type: 'mini-game' },
        { card: '2', rule: 'Dupla Escolha: Escolha DUAS pessoas para beberem.', type: 'target' },
        { card: '3', rule: 'Azar no Jogo: Conte uma piada. Ninguém riu? Beba.', type: 'self' },
        { card: '4', rule: 'Chão: O último a tocar o chão bebe.', type: 'action' },
        { card: '5', rule: 'Mestre da Memória: Repita a sequência de palavras.', type: 'mini-game' },
        { card: '6', rule: 'O Viking: Faça chifres. O último a imitar rema.', type: 'action' },
        { card: '7', rule: 'PI: Múltiplos de 7 ou com 7 são "PI".', type: 'mini-game' },
        { card: '8', rule: 'Olhar Fatal: Escolha alguém para te encarar ao beber.', type: 'target' },
        { card: '9', rule: 'A Bula: Conte uma mentira. Se acreditarem, eles bebem.', type: 'mini-game' },
        { card: '10', rule: 'A Marca: Fale slogans de marcas.', type: 'mini-game' },
        { card: '📸', rule: 'Paparazzi: Pose para foto. Pior pose bebe.', type: 'action' },
        { card: '🔄', rule: 'O Espelho: Quem mandar você beber, bebe no seu lugar.', type: 'self' },
        { card: '🕺', rule: 'Estátua: Fique parado. O primeiro a mexer bebe.', type: 'action' },
        { card: '🐣', rule: 'O Menor: A pessoa mais baixa bebe.', type: 'action' },
        { card: '🗿', rule: 'O Maior: A pessoa mais alta bebe.', type: 'action' },
        { card: '🤡', rule: 'O Palhaço: Faça rir em 10s ou beba.', type: 'self' },
        { card: '💑', rule: 'Casal 20: O casal da roda bebe junto.', type: 'action' },
        { card: '🎲', rule: 'Sorte ou Revés: Cara você bebe, Coroa escolhe.', type: 'self' },

        // --- NÍVEL: PROHIBITED (Regras contínuas "Boss", Drinking Games pesados) ---
        // Nota: Seu filtro 'fun' exclui 'boss', então estes aparecem apenas em Prohibited/Chaos
        { card: '5', rule: 'A Regra: Crie uma regra. Quem quebrar, bebe.', type: 'boss' },
        { card: 'J', rule: 'O Dedinho: Dedão na mesa. O último a notar bebe.', type: 'boss' },
        { card: 'Q', rule: 'O Fantasma: Ninguém pode falar com você.', type: 'boss' },
        { card: 'K', rule: 'O REI: Vire o copo central de uma vez!', type: 'boss' },
        { card: '🃏', rule: 'Mão Trocada: Beba com a mão esquerda.', type: 'boss' },
        { card: '🔇', rule: 'Silêncio Absoluto: Ninguém fala até a próxima carta.', type: 'boss' },
        { card: '👑', rule: 'O Ditador: Você manda beber quando quiser.', type: 'boss' },
        { card: '🚽', rule: 'Pausa pro Xixi: 1 min para ir e voltar.', type: 'boss' }, // Classificado como boss pois altera fluxo

        // --- NÍVEL: CHAOS (Pressão total, Invasão de privacidade) ---
        // Nota: Seu filtro 'prohibited' exclui 'chaos', então estes aparecem SÓ no Chaos
        { card: '☠️', rule: 'MORTE SÚBITA: Todos viram o copo AGORA!', type: 'chaos' },
        { card: '🔥', rule: 'Eu Nunca Relâmpago: Quem já fez, bebe.', type: 'chaos' },
        { card: '💊', rule: 'A Pílula: Beba 2 doses ou fique mudo.', type: 'chaos' },
        { card: '📱', rule: 'Roleta Russa: Passe o celular desbloqueado.', type: 'chaos' }
    ],
        tribunal: [
        // ==============================================================================
        // NÍVEL: FUN (Dilemas Hipotéticos, Dinheiro vs. Conforto, Fama)
        // ==============================================================================
        { text: "Você aceitaria usar apenas roupas de palhaço pelo resto da vida por R$ 10 milhões?", level: 'fun' },
        { text: "Você passaria 1 ano sem internet em troca de uma casa própria quitada?", level: 'fun' },
        { text: "Você aceitaria ter o histórico de navegação publicado no Instagram por R$ 50 mil?", level: 'fun' },
        { text: "Você tatuaria a logo da Havan na testa por R$ 5 milhões?", level: 'fun' },
        { text: "Você aceitaria nunca mais sentir o gosto de comida (só nutrição) para ter o corpo perfeito?", level: 'fun' },
        { text: "Você venderia sua conta do Instagram (com todas as DMs) por R$ 20 mil?", level: 'fun' },
        { text: "Você aceitaria ser mundialmente famoso, mas conhecido como 'A pessoa que cagou na live'?", level: 'fun' },
        { text: "Você ficaria 1 ano sem escovar os dentes por R$ 100 mil?", level: 'fun' },
        { text: "Você aceitaria que todos os seus pensamentos aparecessem num balão sobre sua cabeça por 1 dia em troca de R$ 1 milhão?", level: 'fun' },
        { text: "Você viveria numa casa de vidro (Big Brother) para sempre em troca de nunca mais trabalhar?", level: 'fun' },
        { text: "Você aceitaria dobrar seu salário, mas seu chefe pode te dar um tapa na cara toda segunda-feira?", level: 'fun' },
        { text: "Você aceitaria nunca mais ouvir música na vida em troca de viajar o mundo de graça para sempre?", level: 'fun' },
        { text: "Você deixaria de tomar banho para sempre (só lencinho umedecido) por R$ 1 milhão?", level: 'fun' },
        { text: "Você aceitaria ter 3 metros de altura ou 50 cm de altura?", level: 'fun' },
        { text: "Você preferiria saber a data da sua morte ou a causa da sua morte?", level: 'fun' },
        { text: "Você aceitaria usar fralda geriátrica visível por 1 ano em troca de um carro zero?", level: 'fun' },
        { text: "Você aceitaria comer a mesma comida (arroz e feijão) em todas as refeições para sempre por R$ 5 mil mensais?", level: 'fun' },
        { text: "Você preferiria ter dedos de salsicha ou pernas de pau?", level: 'fun' },
        { text: "Você aceitaria que toda vez que você mentisse, um passarinho defecasse na sua cabeça?", level: 'fun' },
        { text: "Você deixaria seus pais escolherem seu namorado(a) pelo resto da vida em troca de herdar uma ilha?", level: 'fun' },
        { text: "Você aceitaria ter que gritar tudo o que fala por 1 ano em troca de quitar todas as suas dívidas?", level: 'fun' },

        // ==============================================================================
        // NÍVEL: PROHIBITED (Relacionamentos, Ética Duvidosa, Pequenas Corrupções)
        // ==============================================================================
        { text: "Você perdoaria uma traição se ganhasse uma viagem para as Maldivas como pedido de desculpas?", level: 'prohibited' },
        { text: "Você aceitaria R$ 50 mil para terminar seu relacionamento atual agora (sem explicação)?", level: 'prohibited' },
        { text: "Você namoraria o(a) ex do seu melhor amigo(a) se soubesse que é a alma gêmea?", level: 'prohibited' },
        { text: "Você aceitaria ser sustentado(a) por alguém que você não ama, mas que paga tudo?", level: 'prohibited' },
        { text: "Você contaria um segredo do seu melhor amigo para salvar seu próprio emprego?", level: 'prohibited' },
        { text: "Você aceitaria R$ 100 mil para dar em cima do namorado(a) de alguém da roda?", level: 'prohibited' },
        { text: "Você vasculharia o celular do seu parceiro(a) se tivesse certeza que não seria pego?", level: 'prohibited' },
        { text: "Você fingiria uma gravidez (ou paternidade) para segurar um milionário?", level: 'prohibited' },
        { text: "Você deletaria todas as fotos do seu ex das redes sociais dele(a) se tivesse a senha?", level: 'prohibited' },
        { text: "Você aceitaria ser amante de um famoso rico só pelos presentes?", level: 'prohibited' },
        { text: "Você deduraria um colega de trabalho que rouba material de escritório para ganhar uma promoção?", level: 'prohibited' },
        { text: "Você casaria com alguém 40 anos mais velho apenas pela herança?", level: 'prohibited' },
        { text: "Você aceitaria R$ 1 milhão, mas nunca mais poderia ver seus amigos atuais?", level: 'prohibited' },
        { text: "Você trairia seu parceiro(a) por uma noite com sua celebridade crush (sem ninguém saber)?", level: 'prohibited' },
        { text: "Você aceitaria que seu parceiro(a) tivesse um caso, desde que ele te desse R$ 10 mil por traição?", level: 'prohibited' },
        { text: "Você vazaria nudes de um desconhecido na internet por R$ 20 mil?", level: 'prohibited' },
        { text: "Você fingiria estar doente (gravemente) para não ser demitido?", level: 'prohibited' },
        { text: "Você aceitaria nunca mais fazer sexo na vida em troca de R$ 10 milhões?", level: 'prohibited' },
        { text: "Você pagaria para alguém seduzir seu parceiro(a) só para testar a fidelidade?", level: 'prohibited' },
        { text: "Você aceitaria ver seus pais transando uma vez para salvar a vida deles?", level: 'prohibited' },

        // ==============================================================================
        // NÍVEL: CHAOS (Crimes, Tabus, Decisões de Vida ou Morte, Cancelamento Real)
        // ==============================================================================
        { text: "Você venderia seu cachorro de estimação por R$ 2 milhões?", level: 'chaos' },
        { text: "Você incriminaria seu melhor amigo por um crime que você cometeu para não ir preso?", level: 'chaos' },
        { text: "Você apertaria um botão que mata uma pessoa aleatória no mundo para ganhar R$ 5 milhões?", level: 'chaos' },
        { text: "Você vazaria um vídeo íntimo seu de propósito para ficar famoso e ir para a Fazenda?", level: 'chaos' },
        { text: "Você aceitaria R$ 1 milhão para dar um soco na cara da sua mãe (com força)?", level: 'chaos' },
        { text: "Você apagaria a existência de um ex-namorado(a) da memória de todos (ele(a) deixa de existir) por R$ 50?", level: 'chaos' },
        { text: "Você transaria com um primo(a) de primeiro grau para salvar a humanidade?", level: 'chaos' },
        { text: "Você aceitaria trabalhar para um cartel de drogas ganhando R$ 100 mil/mês (sem risco de prisão)?", level: 'chaos' },
        { text: "Você deixaria uma criança desconhecida morrer para salvar seu animal de estimação?", level: 'chaos' },
        { text: "Você aceitaria comer carne humana (bem preparada) por curiosidade?", level: 'chaos' },
        { text: "Você venderia um órgão (rim) saudável por R$ 500 mil no mercado negro?", level: 'chaos' },
        { text: "Você aceitaria que seu filho fosse trocado na maternidade por um bebê mais bonito?", level: 'chaos' },
        { text: "Você dormiria com o chefe do seu parceiro(a) para garantir que ele(a) fosse promovido?", level: 'chaos' },
        { text: "Você aceitaria passar 5 anos na cadeia (com regalias) em troca de R$ 50 milhões na saída?", level: 'chaos' },
        { text: "Você deixaria de falar com sua família para sempre por R$ 1 bilhão?", level: 'chaos' },
        { text: "Você aceitaria ter o poder de matar pessoas com o pensamento (Death Note), mas perderia 1 ano de vida a cada morte?", level: 'chaos' },
        { text: "Você transaria com a pessoa à sua direita agora por R$ 1 milhão?", level: 'chaos' },
        { text: "Você aceitaria ser imortal, mas ver todos que você ama morrerem?", level: 'chaos' },
        { text: "Você roubaria o dinheiro de tratamento médico de um desconhecido para comprar uma Ferrari?", level: 'chaos' },
        { text: "Você aceitaria viver em um mundo onde não existe lei (O Expurgo) por 24h?", level: 'chaos' }
    ],
provavel: [
        // ==============================================================================
        // NÍVEL: FUN (Estereótipos, Desastres Cotidianos, Personalidade, Tecnologia)
        // ==============================================================================
        { text: "Quem morreria primeiro num filme de terror (o que vai investigar o barulho)?", level: 'fun' },
        { text: "Quem sobreviveria a um apocalipse zumbi por pura sorte?", level: 'fun' },
        { text: "Quem viraria um meme nacional por fazer algo estúpido na TV?", level: 'fun' },
        { text: "Quem entraria no Big Brother Brasil e sairia com 99% de rejeição?", level: 'fun' },
        { text: "Quem choraria porque o pedido do iFood veio errado?", level: 'fun' },
        { text: "Quem tropeçaria no nada e cairia no meio da balada?", level: 'fun' },
        { text: "Quem esqueceria o próprio aniversário?", level: 'fun' },
        { text: "Quem gastaria todo o salário no primeiro dia do mês?", level: 'fun' },
        { text: "Quem acredita em teorias da conspiração (Terra Plana, ETs)?", level: 'fun' },
        { text: "Quem seria expulso de um funeral por rir na hora errada?", level: 'fun' },
        { text: "Quem tem o histórico de pesquisa do Google mais bizarro?", level: 'fun' },
        { text: "Quem seria enganado por um golpe do WhatsApp pedindo Pix?", level: 'fun' },
        { text: "Quem largaria tudo para viver de vender miçanga na praia?", level: 'fun' },
        { text: "Quem tem mais chance de virar um acumulador (tipo programa de TV)?", level: 'fun' },
        { text: "Quem fala sozinho em público sem perceber?", level: 'fun' },
        { text: "Quem demoraria 3 horas para contar uma história de 5 minutos?", level: 'fun' },
        { text: "Quem seria barrado na imigração de outro país por parecer suspeito?", level: 'fun' },
        { text: "Quem tem a risada mais engraçada (ou irritante)?", level: 'fun' },
        { text: "Quem nunca entende a piada e ri por educação?", level: 'fun' },
        { text: "Quem ficaria famoso no TikTok fazendo dancinha ridícula?", level: 'fun' },
        { text: "Quem perderia o voo porque estava tomando café no aeroporto?", level: 'fun' },
        { text: "Quem adotaria 10 gatos se ficasse solteiro(a)?", level: 'fun' },
        { text: "Quem gritaria ao ver uma barata voando?", level: 'fun' },
        { text: "Quem seria confundido com um mendigo pelo estilo de roupa?", level: 'fun' },
        { text: "Quem vai ficar careca primeiro?", level: 'fun' },
        { text: "Quem passaria 1 semana sem tomar banho se ninguém notasse?", level: 'fun' },
        { text: "Quem comeria comida do lixo se estivesse embalada?", level: 'fun' },
        { text: "Quem tem mais chance de quebrar o celular na primeira semana de uso?", level: 'fun' },
        { text: "Quem seria preso por engano?", level: 'fun' },
        { text: "Quem ganharia na loteria e perderia o bilhete?", level: 'fun' },
        { text: "Quem tem medo de dormir no escuro?", level: 'fun' },
        { text: "Quem passa mais tempo sentado no vaso sanitário vendo Instagram?", level: 'fun' },
        { text: "Quem nunca responde mensagens no WhatsApp?", level: 'fun' },
        { text: "Quem manda áudios de 5 minutos para contar algo simples?", level: 'fun' },
        { text: "Quem compraria um curso de 'Como ficar rico' e ficaria mais pobre?", level: 'fun' },
        { text: "Quem casaria com um personagem de anime/jogo se pudesse?", level: 'fun' },
        { text: "Quem vai virar a 'Tia/Tio dos Gatos'?", level: 'fun' },
        { text: "Quem vai morar com os pais até os 40 anos?", level: 'fun' },
        { text: "Quem tem mais chance de tropeçar e derrubar o bolo de casamento?", level: 'fun' },
        { text: "Quem chora vendo propaganda de margarina?", level: 'fun' },
        { text: "Quem seria cancelado no Twitter por um tweet de 2010?", level: 'fun' },
        { text: "Quem tem a letra mais feia?", level: 'fun' },
        { text: "Quem vai ter 5 filhos?", level: 'fun' },
        { text: "Quem nunca paga a conta na hora certa?", level: 'fun' },
        { text: "Quem pede comida e come a batata frita dos outros?", level: 'fun' },
        { text: "Quem vai ser o primeiro a dormir na festa?", level: 'fun' },
        { text: "Quem tem mais chance de virar vegano chato?", level: 'fun' },
        { text: "Quem gastaria todo o limite do cartão de crédito em brusinha/jogos?", level: 'fun' },
        { text: "Quem tem o nome mais sujo no Serasa?", level: 'fun' },

        // ==============================================================================
        // NÍVEL: PROHIBITED (Bebida, Relacionamentos Tóxicos, Vergonha, Pegação)
        // ==============================================================================
        { text: "Quem daria PT (Perda Total) antes da meia-noite?", level: 'prohibited' },
        { text: "Quem voltaria com o(a) ex tóxico(a) amanhã se ele(a) chamasse?", level: 'prohibited' },
        { text: "Quem tem mais chance de acordar em outra cidade depois de beber?", level: 'prohibited' },
        { text: "Quem beijaria o porteiro/segurança da balada?", level: 'prohibited' },
        { text: "Quem tem o pior gosto para namorado(a) (Dedo Podre)?", level: 'prohibited' },
        { text: "Quem mandaria nudes para o grupo da família sem querer?", level: 'prohibited' },
        { text: "Quem seria preso por fazer xixi na rua?", level: 'prohibited' },
        { text: "Quem stalkeia o ex obsessivamente (sabe até o CPF)?", level: 'prohibited' },
        { text: "Quem chora no Uber contando a vida pro motorista?", level: 'prohibited' },
        { text: "Quem tatuaria o nome de alguém que conheceu há 1 semana?", level: 'prohibited' },
        { text: "Quem ficaria com alguém só pelo carro/dinheiro?", level: 'prohibited' },
        { text: "Quem beijaria 5 pessoas na mesma noite?", level: 'prohibited' },
        { text: "Quem sumiria da festa sem dar tchau pra ninguém?", level: 'prohibited' },
        { text: "Quem arrumaria briga na fila do banheiro?", level: 'prohibited' },
        { text: "Quem vomitaria no carro do amigo?", level: 'prohibited' },
        { text: "Quem se apaixonaria pelo stripper na despedida de solteiro?", level: 'prohibited' },
        { text: "Quem tem mais chance de ter um vídeo vergonhoso viralizado?", level: 'prohibited' },
        { text: "Quem manda mensagem 'oi sumido' quando está carente?", level: 'prohibited' },
        { text: "Quem fingiria uma gravidez (ou doença) para segurar o namoro?", level: 'prohibited' },
        { text: "Quem transaria no primeiro encontro e se apegaria?", level: 'prohibited' },
        { text: "Quem seria expulso do bar por subir na mesa?", level: 'prohibited' },
        { text: "Quem gastaria o dinheiro do aluguel em bebida?", level: 'prohibited' },
        { text: "Quem nunca devolve as roupas que pegou emprestado?", level: 'prohibited' },
        { text: "Quem tem a vida amorosa mais caótica?", level: 'prohibited' },
        { text: "Quem seria banido do Tinder por comportamento inadequado?", level: 'prohibited' },
        { text: "Quem tem mais chance de pegar uma DST?", level: 'prohibited' },
        { text: "Quem transaria no banheiro do trabalho?", level: 'prohibited' },
        { text: "Quem namoraria alguém 20 anos mais velho por interesse?", level: 'prohibited' },
        { text: "Quem ficaria com o ex do melhor amigo?", level: 'prohibited' },
        { text: "Quem tem nudes salvos no celular agora?", level: 'prohibited' },
        { text: "Quem mandaria nudes sem mostrar o rosto 'por segurança'?", level: 'prohibited' },
        { text: "Quem seria pego fazendo sexo em público?", level: 'prohibited' },
        { text: "Quem chora depois de transar?", level: 'prohibited' },
        { text: "Quem finge orgasmo com frequência?", level: 'prohibited' },
        { text: "Quem tem fama de beijar mal?", level: 'prohibited' },
        { text: "Quem tem o fetiche mais estranho?", level: 'prohibited' },
        { text: "Quem trairia e colocaria a culpa na bebida?", level: 'prohibited' },
        { text: "Quem já ficou com alguém comprometido sabendo?", level: 'prohibited' },
        { text: "Quem tem um perfil fake só para stalkear?", level: 'prohibited' },
        { text: "Quem bloqueia e desbloqueia o ex 10 vezes por dia?", level: 'prohibited' },
        { text: "Quem daria o golpe da barriga?", level: 'prohibited' },
        { text: "Quem fica insuportável quando bebe?", level: 'prohibited' },
        { text: "Quem tira a roupa quando fica bêbado?", level: 'prohibited' },
        { text: "Quem ligaria para o ex chorando agora?", level: 'prohibited' },
        { text: "Quem beijaria alguém do mesmo sexo (sendo hétero) bêbado?", level: 'prohibited' },
        { text: "Quem vai casar e divorciar 3 vezes?", level: 'prohibited' },
        { text: "Quem tem um 'Sugar Daddy' ou 'Sugar Mommy' escondido?", level: 'prohibited' },
        { text: "Quem vai ser preso por desacato à autoridade?", level: 'prohibited' },
        { text: "Quem postaria foto chorando no Instagram?", level: 'prohibited' },

        // ==============================================================================
        // NÍVEL: CHAOS (Crime, Talaricagem Extrema, Moral Duvidosa, Psicopatia)
        // ==============================================================================
        { text: "Quem seria preso primeiro?", level: 'chaos' },
        { text: "Quem casaria por dinheiro com alguém de 90 anos?", level: 'chaos' },
        { text: "Quem mataria alguém por acidente e pediria ajuda pra esconder o corpo?", level: 'chaos' },
        { text: "Quem abriria um OnlyFans e ficaria rico?", level: 'chaos' },
        { text: "Quem 'talaricaria' (pegaria) o namorado(a) do melhor amigo?", level: 'chaos' },
        { text: "Quem forjaria a própria morte para fugir das dívidas?", level: 'chaos' },
        { text: "Quem entraria para uma seita e tentaria recrutar todo mundo?", level: 'chaos' },
        { text: "Quem tem mais cara de psicopata escondido?", level: 'chaos' },
        { text: "Quem venderia o amigo por 1 milhão de reais?", level: 'chaos' },
        { text: "Quem teria um filho e não saberia quem é o pai/mãe?", level: 'chaos' },
        { text: "Quem seria o vilão numa novela?", level: 'chaos' },
        { text: "Quem tem segredos que destruiriam a vida de todos aqui?", level: 'chaos' },
        { text: "Quem seria preso por fraude ou lavagem de dinheiro?", level: 'chaos' },
        { text: "Quem tem mais chance de ter uma vida dupla (outra família)?", level: 'chaos' },
        { text: "Quem vazaria a sex tape de propósito para ficar famoso?", level: 'chaos' },
        { text: "Quem seria capaz de envenenar alguém por vingança?", level: 'chaos' },
        { text: "Quem transaria com um primo(a) distante?", level: 'chaos' },
        { text: "Quem roubaria algo de uma loja só pela adrenalina?", level: 'chaos' },
        { text: "Quem seria um Sugar Baby profissional?", level: 'chaos' },
        { text: "Quem deixaria o amigo ser preso para se salvar?", level: 'chaos' },
        { text: "Quem tem o fetiche mais bizarro e inconfessável?", level: 'chaos' },
        { text: "Quem daria o golpe do baú?", level: 'chaos' },
        { text: "Quem vai pro inferno com certeza?", level: 'chaos' },
        { text: "Quem seria capaz de hackear o celular do namorado(a)?", level: 'chaos' },
        { text: "Quem seria o primeiro a recorrer ao canibalismo numa ilha deserta?", level: 'chaos' },
        { text: "Quem transaria com o pai/mãe de um amigo?", level: 'chaos' },
        { text: "Quem venderia nudes dos amigos na internet?", level: 'chaos' },
        { text: "Quem falsificaria um teste de DNA?", level: 'chaos' },
        { text: "Quem seria capaz de matar por dinheiro?", level: 'chaos' },
        { text: "Quem colocaria fogo na casa do ex?", level: 'chaos' },
        { text: "Quem traficaria drogas internacionalmente sem querer?", level: 'chaos' },
        { text: "Quem tem um cadáver no porta-malas (metaforicamente ou não)?", level: 'chaos' },
        { text: "Quem vai ser o primeiro a ser processado?", level: 'chaos' },
        { text: "Quem fingiria amizade só para destruir alguém?", level: 'chaos' },
        { text: "Quem roubaria a herança dos irmãos?", level: 'chaos' },
        { text: "Quem transaria em um velório?", level: 'chaos' },
        { text: "Quem seria banido de um país?", level: 'chaos' },
        { text: "Quem criaria um esquema de pirâmide?", level: 'chaos' },
        { text: "Quem abandonaria o filho se ele fosse feio?", level: 'chaos' },
        { text: "Quem tem mais chance de virar um serial killer?", level: 'chaos' },
        { text: "Quem chantagearia alguém com fotos íntimas?", level: 'chaos' },
        { text: "Quem dormiria com o chefe para ser promovido?", level: 'chaos' },
        { text: "Quem mentiria no tribunal sob juramento?", level: 'chaos' },
        { text: "Quem seria capaz de roubar o namorado(a) da irmã(o)?", level: 'chaos' },
        { text: "Quem vai morrer sozinho cercado de dinheiro?", level: 'chaos' },
        { text: "Quem vende a própria dignidade por um iPhone?", level: 'chaos' },
        { text: "Quem tem a alma mais podre?", level: 'chaos' },
        { text: "Quem seria o líder de uma gangue?", level: 'chaos' }
    ],
};